---
author:
  email: 
  name: An Author
  twitter: 
  url: 
baseurl: "/readux-text-0211"
collections:
  annotations:
    output: true
    permalink: "/annotations/:path/"
  volume_pages:
    output: true
    permalink: "/pages/:path/"
defaults:
- scope:
    path: ''
    type: volume_pages
  values:
    layout: volume_page
    short_label: p.
    deep_zoom: true
    extra_js:
    - volume-page.js
    - hammer.min.js
    - deepzoom.js
    - openseadragon.min.js
- scope:
    path: ''
    type: annotations
  values:
    layout: annotation
description: An annotated digital edition created with <a href="http://readux.library.emory.edu/">Readux</a>
gems:
- jekyll-sitemap
homepage_image: https://iiif.archivelab.org/iiif/32862204.5243.emory.edu$0/full/full/0/default.jpg
image_size:
  page:
    width: 3900
    height: 3113
permalink: pretty
publication_info:
  title: Fouilles sur le Palatin dans les jardins farnèses appartenent a s.m. l'empereur
    Napoléo
  date: '2020'
  editors: []
show_annotation_author: true
source_info:
  title: Fouilles sur le Palatin dans les jardins farnèses appartenent a s.m. l'empereur
    Napoléo
  via_readux: true
tagline: an annotated digital edition
title: Fouilles sur le Palatin dans les jardins farnèses appartenent a s.m. l'empereur
  Napoléo
url: https://saracarl.github.io
version: 0.7
